---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04

suites:
  - name: default
    run_list: recipe[locale]
    attributes:
      locale:
        lang: "en_AU.utf8"
        lc_all: "en_AU.utf8"
